services:
  project:
    build:
      context: .
      dockerfile: FinancialStatisticsAdminiculum.Api/Dockerfile
    ports:
      - "5000:8080"
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LocalConnection=Host=db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq:80/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - RabbitMQ__Host=RabbitMQ
    depends_on:
      db:
        condition: service_healthy
      seq:
        condition: service_started
      api:
        condition: service_healthy
      RabbitMQ:
        condition: service_healthy
    networks:
      - backend
    restart: always

  web:
    build:
      context: ./FinancialStatisticsAdminiculum.Web
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - project
    networks:
      - backend
    restart: always

  db:
    image: postgres:16-alpine
    shm_size: 128mb
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    restart: always

  seq:
    image: datalust/seq:latest
    env_file: .env
    environment: 
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    networks:
      - backend
    restart: always
  
  RabbitMQ:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - backend
    restart: always

  api:
    build:
      context: .
      dockerfile: FunctionGemma.Api/Dockerfile
    networks:
      - backend
    depends_on:
      RabbitMQ:
        condition: service_healthy
    environment:
      - Paths__modelPath=/app/models/functiongemma_oga
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq:80/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - RabbitMQ__Host=RabbitMQ
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always


volumes:
  db_data:
  seq_data:

networks:
  backend:
