// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialStatisticsAdminiculum.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316233405_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialStatisticsAdminiculum.Core.Entities.Asset", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Ticker");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("FinancialStatisticsAdminiculum.Core.Entities.PricePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetTicker")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTicker", "Timestamp");

                    b.ToTable("PricePoints", (string)null);
                });

            modelBuilder.Entity("FinancialStatisticsAdminiculum.Core.Entities.PricePoint", b =>
                {
                    b.HasOne("FinancialStatisticsAdminiculum.Core.Entities.Asset", null)
                        .WithMany("MarketData")
                        .HasForeignKey("AssetTicker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialStatisticsAdminiculum.Core.Entities.Asset", b =>
                {
                    b.Navigation("MarketData");
                });
#pragma warning restore 612, 618
        }
    }
}
